In [3]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics import confusion_matrix
from keras.models import Sequential
from keras.layers import Dense, Dropout

In [6]:
spam = pd.read_csv("spam.csv")
spam.head(3)

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...

In [8]:
label_encoder = LabelEncoder()
y = label_encoder.fit_transform(spam.Category)
y

array([0, 0, 1, ..., 0, 0, 0])

In [24]:
X = spam.Message.values
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [25]:
vector = CountVectorizer()
vector.fit(X_train)

X_train = vector.transform(X_train)
X_test = vector.transform(X_test)
print(X_train.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [29]:
import numpy as np
np.set_printoptions(threshold=np.inf)

In [30]:
print(X_train.toarray()[0])

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 

### Model

In [35]:
X_train.shape[1]

7538

In [32]:
model = Sequential()

In [36]:
model.add(Dense(units=10,activation="relu",input_dim=X_train.shape[1]))
model.add(Dropout(0.1))
model.add(Dense(units=8,activation="relu"))
model.add(Dropout(0.1))
model.add(Dense(units=1,activation="sigmoid"))

C:\Users\znaya\anaconda1\lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [37]:
model.compile(loss="mean_squared_error", optimizer="adam",metrics=["accuracy"])
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 10)             │        75,390 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 10)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 8)              │            88 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 8)              │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │             9 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 75,487 (294.87 KB)

 Trainable params: 75,487 (294.87 KB)

 Non-trainable params: 0 (0.00 B)

In [38]:
model.fit(X_train, y_train, epochs=20,batch_size=10,verbose=True,validation_data=(X_test,y_test))

Epoch 1/20
418/418 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - accuracy: 0.8674 - loss: 0.1474 - val_accuracy: 0.9849 - val_loss: 0.0174
Epoch 2/20
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9857 - loss: 0.0167 - val_accuracy: 0.9871 - val_loss: 0.0111
Epoch 3/20
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9958 - loss: 0.0064 - val_accuracy: 0.9892 - val_loss: 0.0104
Epoch 4/20
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9952 - loss: 0.0054 - val_accuracy: 0.9864 - val_loss: 0.0107
Epoch 5/20
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9980 - loss: 0.0031 - val_accuracy: 0.9885 - val_loss: 0.0099
Epoch 6/20
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9981 - loss: 0.0022 - val_accuracy: 0.9849 - val_loss: 0.0112
Epoch 7/20
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9981 - loss: 0.0019 - val_accuracy: 0.9842 - val_loss: 0.0124
Epoch 8/20
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9994 - loss: 9.9939e-04 - val_accuracy

In [39]:
loss, acc = model.evaluate(X_test, y_test)
print(f"Loss: {loss}\nAccuracy: {acc}")

44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 744us/step - accuracy: 0.9865 - loss: 0.0124   
Loss: 0.015275171957910061
Accuracy: 0.9827709794044495


In [40]:
y_pred = model.predict(X_test)
print(y_pred)

44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
[[3.68667155e-04]
 [1.19925699e-06]
 [9.99999821e-01]
 [1.01207488e-03]
 [1.50254607e-04]
 [2.10845897e-07]
 [1.67010739e-06]
 [3.69693189e-05]
 [6.58262870e-04]
 [1.10232702e-03]
 [6.03670545e-04]
 [9.46522690e-04]
 [6.11222640e-04]
 [5.28666222e-09]
 [2.06882905e-05]
 [1.47407636e-14]
 [1.82605777e-06]
 [1.37685216e-04]
 [9.99998033e-01]
 [1.68449276e-07]
 [7.35237450e-07]
 [1.98241414e-05]
 [2.37327413e-06]
 [1.41228214e-04]
 [4.48568782e-09]
 [9.99999642e-01]
 [2.11983547e-06]
 [1.18213705e-08]
 [2.89334753e-06]
 [9.57906013e-05]
 [6.13801603e-07]
 [1.83158189e-09]
 [4.59521885e-16]
 [1.65903816e-06]
 [2.25017420e-13]
 [3.31233377e-06]
 [9.05071573e-09]
 [1.09788916e-08]
 [5.89839260e-07]
 [1.30456249e-06]
 [1.03826773e-04]
 [3.97154008e-06]
 [8.43258167e-05]
 [1.43452053e-06]
 [9.99998927e-01]
 [2.96855462e-04]
 [1.56885460e-02]
 [4.34934935e-11]
 [1.34534703e-05]
 [9.99999821e-01]
 [2.39588753e-05]
 [2.69190366e-07]
 [4.23985395e-11]
 [2.551

In [41]:
print(y_pred > 0.5)

[[False]
 [False]
 [ True]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [ True]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [ True]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [ True]
 [False]
 [False]
 [False]
 [False]
 [ True]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [ True]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [ True]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [ True]
 [False]
 [False]
 [False]
 [False]
 [ True]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [ True]
 [False]
 [False]
 [False]
 [ True]
 

In [43]:
print(confusion_matrix(y_test,y_pred > 0.5))

[[1213    5]
 [  19  156]]
